config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorite, only: [:create, :destroy]
  end

  get "search" => "searches#search"

  resources :users, only: [:index,:show,:edit,:update,] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

 resources :chats, only: [:show, :create, :destroy]

 get 'tagsearches/search', to: 'tagsearches#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #cd bookers2-debug-b
  #bundle exec rspec spec/ --format documentation
  #rails routes
end
                                  #search GET    /search(.:format)                                                                                 searches#search
                         #user_followings GET    /users/:user_id/followings(.:format)                                                              relationships#followings
                          #user_followers GET    /users/:user_id/followers(.:format)                                                               relationships#followers
                        #new_user_session GET    /users/sign_in(.:format)                                                                          devise/sessions#new
                            #user_session POST   /users/sign_in(.:format)                                                                          devise/sessions#create
                    #destroy_user_session DELETE /users/sign_out(.:format)                                                                         devise/sessions#destroy
                       #new_user_password GET    /users/password/new(.:format)                                                                     devise/passwords#new
                      #edit_user_password GET    /users/password/edit(.:format)                                                                    devise/passwords#edit
                           #user_password PATCH  /users/password(.:format)                                                                         devise/passwords#update
                                         #PUT    /users/password(.:format)                                                                         devise/passwords#update
                                         #POST   /users/password(.:format)                                                                         devise/passwords#create
                #cancel_user_registration GET    /users/cancel(.:format)                                                                           devise/registrations#cancel
                   #new_user_registration GET    /users/sign_up(.:format)                                                                          devise/registrations#new
                  #edit_user_registration GET    /users/edit(.:format)                                                                             devise/registrations#edit
                       #user_registration PATCH  /users(.:format)                                                                                  devise/registrations#update
                                         #PUT    /users(.:format)                                                                                  devise/registrations#update
                                         #DELETE /users(.:format)                                                                                  devise/registrations#destroy
                                         #POST   /users(.:format)                                                                                  devise/registrations#create
                                    #root GET    /                                                                                                 homes#top
                              #home_about GET    /home/about(.:format)                                                                             homes#about
                                   #books GET    /books(.:format)                                                                                  books#index
                                         #POST   /books(.:format)                                                                                  books#create
                               #edit_book GET    /books/:id/edit(.:format)                                                                         books#edit
                                    #book GET    /books/:id(.:format)                                                                              books#show
                                         #PATCH  /books/:id(.:format)                                                                              books#update
                                         #PUT    /books/:id(.:format)                                                                              books#update
                                         #DELETE /books/:id(.:format)                                                                              books#destroy
                                   #users GET    /users(.:format)                                                                                  users#index
                               #edit_user GET    /users/:id/edit(.:format)                                                                         users#edit
                                    #user GET    /users/:id(.:format)                                                                              users#show
                                         #PATCH  /users/:id(.:format)                                                                              users#update
                                         #PUT    /users/:id(.:format)                                                                              users#update
                           #book_favorite DELETE /books/:book_id/favorite(.:format)                                                                favorites#destroy
                                         #POST   /books/:book_id/favorite(.:format)                                                                favorites#create
                      #book_book_comments POST   /books/:book_id/book_comments(.:format)                                                           book_comments#create

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_many :books
has_many :book_comments, dependent: :destroy
has_many :favorites, dependent: :destroy

  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :rooms, through: :user_rooms

has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

# 一覧画面で使う
has_many :followings, through: :relationships, source: :followed
has_many :followers, through: :reverse_of_relationships, source: :follower

  has_one_attached :profile_image
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }


def follow(user_id)
  relationships.create(followed_id: user_id)
end
# フォローを外すときの処理
def unfollow(user_id)
  relationships.find_by(followed_id: user_id).destroy
end
# フォローしているか判定
def following?(user)
  followings.include?(user)
end


  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @users = User.all
  end

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  def edit
   @user = User.find(params[:id])
   @book = @user
  end

  def update
     @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      @books = Book.all
      @book = Book.new
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td><% if current_user.following?(user) %>
         <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
          <% else %>
         <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
        <% end %>
        </td>
        <td><%= link_to 'Show', user %></td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>
<div class='row'>

  <% if user.id == current_user.id %>

  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>

  <% else %>

   <% if current_user.following?(user) %>
    <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-primary" %>
   <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: 'btn btn-success' %>
   <% end %>

  <% end %>
  <% if current_user != user && current_user.following?(user) && user.following?(current_user) %>
    <%= link_to 'chatを始める', chat_path(user.id), class: "ml-3" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <%= render 'layouts/errors', user: @user %>
    <h2>User info</h2>
    <%= form_with model: @user, local:true do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
<h2>User info</h2>
<%= render 'info', user: current_user %>

<h2 class="mt-3">New book</h2>
<%= render 'books/form', book: @book %>
</div>
    <div class='col-md-8 offset-md-1'>
<h2>Users</h2>
<%= render 'users/index',users: @users %>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>

      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>