config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorite, only: [:create, :destroy]
  end

  get "search" => "searches#search"

  resources :users, only: [:index,:show,:edit,:update,] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

 resources :chats, only: [:show, :create, :destroy]

 get 'tagsearches/search', to: 'tagsearches#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #cd bookers2-debug-b
  #bundle exec rspec spec/ --format documentation
  #rails routes
end
                                  #search GET    /search(.:format)                                                                                 searches#search
                         #user_followings GET    /users/:user_id/followings(.:format)                                                              relationships#followings
                          #user_followers GET    /users/:user_id/followers(.:format)                                                               relationships#followers
                        #new_user_session GET    /users/sign_in(.:format)                                                                          devise/sessions#new
                            #user_session POST   /users/sign_in(.:format)                                                                          devise/sessions#create
                    #destroy_user_session DELETE /users/sign_out(.:format)                                                                         devise/sessions#destroy
                       #new_user_password GET    /users/password/new(.:format)                                                                     devise/passwords#new
                      #edit_user_password GET    /users/password/edit(.:format)                                                                    devise/passwords#edit
                           #user_password PATCH  /users/password(.:format)                                                                         devise/passwords#update
                                         #PUT    /users/password(.:format)                                                                         devise/passwords#update
                                         #POST   /users/password(.:format)                                                                         devise/passwords#create
                #cancel_user_registration GET    /users/cancel(.:format)                                                                           devise/registrations#cancel
                   #new_user_registration GET    /users/sign_up(.:format)                                                                          devise/registrations#new
                  #edit_user_registration GET    /users/edit(.:format)                                                                             devise/registrations#edit
                       #user_registration PATCH  /users(.:format)                                                                                  devise/registrations#update
                                         #PUT    /users(.:format)                                                                                  devise/registrations#update
                                         #DELETE /users(.:format)                                                                                  devise/registrations#destroy
                                         #POST   /users(.:format)                                                                                  devise/registrations#create
                                    #root GET    /                                                                                                 homes#top
                              #home_about GET    /home/about(.:format)                                                                             homes#about
                                   #books GET    /books(.:format)                                                                                  books#index
                                         #POST   /books(.:format)                                                                                  books#create
                               #edit_book GET    /books/:id/edit(.:format)                                                                         books#edit
                                    #book GET    /books/:id(.:format)                                                                              books#show
                                         #PATCH  /books/:id(.:format)                                                                              books#update
                                         #PUT    /books/:id(.:format)                                                                              books#update
                                         #DELETE /books/:id(.:format)                                                                              books#destroy
                                   #users GET    /users(.:format)                                                                                  users#index
                               #edit_user GET    /users/:id/edit(.:format)                                                                         users#edit
                                    #user GET    /users/:id(.:format)                                                                              users#show
                                         #PATCH  /users/:id(.:format)                                                                              users#update
                                         #PUT    /users/:id(.:format)                                                                              users#update
                           #book_favorite DELETE /books/:book_id/favorite(.:format)                                                                favorites#destroy
                                         #POST   /books/:book_id/favorite(.:format)                                                                favorites#create
                      #book_book_comments POST   /books/:book_id/book_comments(.:format)                                                           book_comments#create

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :week_favorites, -> { where(created_at: 1.week.ago.beginning_of_day..Time.current.end_of_day) }
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }



  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end

  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  scope :star_count, -> {order(star: :desc)}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :is_matching_login_user, only: [:edit, :update]

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
    @books = Book.all
    @newbook = Book.new
    @book.increment!(:view_count)
  end

  def index
  to = Time.current.at_end_of_day
  from = (to - 6.day).at_beginning_of_day
  
  
  if params[:latest]
     @books = Book.latest
  elsif params[:old]
     @books = Book.old
  elsif params[:star_count]
     @books = Book.star_count
  else
     @books = Book.includes(:favorites).sort_by { |book| -book.favorites.where(created_at: from...to).count }
  end
  
    @user = current_user
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    @user = current_user
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :star, :category)
  end

  def is_matching_login_user
    book = Book.find(params[:id])
    user = book.user
    unless user.id == current_user.id
      redirect_to books_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model: book do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
<% if book.id.nil? %>
    <div class="form-group" id="star">
      <%= f.label :star %>
      <%= f.hidden_field :star, id: :review_star, class: 'form-control' %>
      <div id="post_raty"></div>
    </div>
    <script>
      $(document).on('turbolinks:load', function() {
        let elem = document.querySelector('#post_raty');
        if (elem == null) return;

        elem.innerHTML = ""
        let opt = {
          starOn: "<%= asset_path('star-on.png') %>",
          starOff: "<%= asset_path('star-off.png') %>",
          starHalf: "<%= asset_path('star-half.png') %>",
          scoreName: 'book[star]',
        };
        raty(elem, opt);
      });
    </script>
  <% else %>
  
    <div class="form-group">
      <%= render "static.rate", book: book %>
    </div>
<% end %>
  <div class="form-group">
  <label>Category</label>
  <%= f.text_field :category,class: 'form-control book_category' %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
  
<% end %>

app/views/books/_index.html.erb
<table class="table table-hover table-inverse">
   <thread>
     <tr>
       <th></th>
       <th>Title</th>
       <th>Opinion</th>
       <th>Tag</th>
       <th></th>
       <th colspan="3"></th>
     </tr>
   </thread>
   <tbody>
     <% books.each do |book| %>
     <tr>
       <td>
         <%= link_to book.user do %>
           <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
       </td>
       <td><%= link_to book.title,book %></td>
       <td><%= book.body %></td>
        <td>       
        <% if book.category.present? %>
          <%=link_to book.category,tagsearches_search_path(content: book.category)%>
        <% end %>
        </td>
       <td id="favorite_btn_<%= book.id %>">
         <%= render "favorites/btn", book: book %>
       </td>
       <td>コメント数： <%= book.book_comments.count %></td>
        <td><%= render "books/static.rate", book: book %></td>
     </tr>
   <% end %>
   </tbody>
 </table>

app/views/books/_static.rate.html.erb
<div id="star_<%= book.id %>"></div>
<script>
$(document).on('turbolinks:load', function() {
  let elem = document.querySelector('#star_<%= book.id %>');
  if (elem == null) return;
  
  elem.innerHTML = "";
  let opt = {  
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    score: "<%= book.star %>",
    readOnly: true,　　　　
  };
  raty(elem, opt);
});
</script>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <%= render 'layouts/errors', user: @book %>
  		<h1>Editing Book</h1>
  	  <%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', user: @book %>
  <div class='row'>
    <div class='col-md-3'>

      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <p>
       <%= link_to '新しい順', books_path(latest: "true") %>
       |<%= link_to '古い順', books_path(old: "true") %>
       |<%= link_to '評価の高い順', books_path(star_count: "true") %>
      </p>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
 <div class="container">
   <div class="row">
     <div class="col-md-3">
       <h2>User info</h2>
       <%= render "users/info", user: @user %>
       <h2 class="mt-3">New book</h2>
       <%= render "form", book: @newbook %>
     </div>
     <div class='col-md-8 offset-md-1'>
       <h2>Book detail</h2>
       <table class="table">
         <tr>
           <td><%= link_to @book.user do %>
               <%= image_tag @book.user.get_profile_image, size:"50x50" %><br>
               <%= @book.user.name %>
               <% end %>
           </td>
           <td><%= link_to @book.title, @book %></td>
           <td><%= @book.body %></td>
           <td>
　　        <% if @book.category.present? %>
　　　      　<%=link_to@book.category,tagsearches_search_path(content:@book.category)%>
　         　<% end %>
           </td>
           <td id="favorite_btn_<%= @book.id %>">
             <%= render "favorites/btn", book: @book %>
           </td>
           <td id="comment_counter">
             <%= render "book_comments/counter", book: @book %>
           </td>
           <td>閲覧数: <%= @book.view_count %></td>

           <% if @book.user == current_user %>
           <td><%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
           <td><%= link_to "Destroy", @book, method: :delete, data: { confirm: "本当に消しますか？" }, class: "btn btn-sm btn-danger" %></td>
           <% end %>
         </tr>
       </table>

       <div id="comment_index">
         <%= render "book_comments/index", book: @book %>
       </div>
       <%= render "book_comments/form", book: @book, book_comment: @book_comment %>

     </div>
   </div>
 </div>